using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SistemaGestionMesas2.Models
{
    public class Product
    {
        // Properties
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; } // Id, identity added, generated by the database

        [Required]
        [Column(TypeName = "VARCHAR(500)")]
        public string Name { get; set; } // Name of the product

        [Required]
        [Column(TypeName = "MONEY")]
        public decimal Price { get; set; } // Price of the product

        public List<TableProduct> TableProducts { get; set; } = new List<TableProduct>();

        // Methods
        public override string ToString()
        {
            return $"{Name}, ${Price:F2}"; 
        }

        // Constructors
        public Product() { }
        public Product(string name, decimal price)
        {
            Name = name;
            Price = price;
        }
    }
}
