// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionMesas2.Data;

#nullable disable

namespace SistemaGestionMesas2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250115144034_Initialization")]
    partial class Initialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionMesas2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("MONEY");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaGestionMesas2.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("SistemaGestionMesas2.Models.TableProduct", b =>
                {
                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TableId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("TableProduct");
                });

            modelBuilder.Entity("SistemaGestionMesas2.Models.Menu", b =>
                {
                    b.HasBaseType("SistemaGestionMesas2.Models.Product");

                    b.Property<int>("TimeToCook")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Menu");
                });

            modelBuilder.Entity("SistemaGestionMesas2.Models.TableProduct", b =>
                {
                    b.HasOne("SistemaGestionMesas2.Models.Product", "Product")
                        .WithMany("TableProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionMesas2.Models.Table", "Table")
                        .WithMany("TableProducts")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SistemaGestionMesas2.Models.Product", b =>
                {
                    b.Navigation("TableProducts");
                });

            modelBuilder.Entity("SistemaGestionMesas2.Models.Table", b =>
                {
                    b.Navigation("TableProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
